app: vjepa
nodes: 1
tasks_per_node: 2
cpus_per_task: 2
mem_per_gpu: 15G
folder: /kaggle/working/logs/jepa
data:
  dataset_type: VideoDataset
  datasets:
  - /kaggle/working/ucf101_train_paths.csv
  datasets_weights:
  - 1.0
  batch_size: 16
  crop_size: 224
  patch_size: 16
  dataset_fpcs:
  - 16
  tubelet_size: 2
  fps: 4
  num_workers: 2
  persistent_workers: true
  pin_mem: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: float16
  eval_freq: 100
  load_checkpoint: true
  read_checkpoint: /kaggle/input/notebooks/dientruong/notebook459d81d101/nano-jepa/logs/2026-06-27_05-41-29-jepa-latest.pth.tar
  save_every_freq: 10
  seed: 234
  use_sdpa: true
model:
  model_name: vit_tiny
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: false
  use_mask_tokens: true
  use_rope: false
  zero_init_mask_tokens: true
optimization:
  ema:
  - 0.998
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe: 3
  ipe_scale: 1.25
  lr: 0.000625
  start_lr: 0.0002
  warmup: 30
  weight_decay: 0.04
