cpus_per_task: 2
eval_name: video_classification_frozen
folder: /kaggle/working/evals/vitl/ucf101
mem_per_gpu: 15G
nodes: 1
num_workers: 2
resume_checkpoint: true
tag: ucf101-vitl16
tasks_per_node: 2
experiment:
  classifier:
    num_heads: 1
    num_probe_blocks: 4
  data:
    dataset_type: VideoDataset
    dataset_train: /kaggle/working/ucf101_train_paths.csv
    dataset_val: /kaggle/working/ucf101_val_paths.csv
    frame_step: 4
    frames_per_clip: 8
    num_classes: 101
    num_segments: 10
    num_views_per_segment: 3
    resolution: 224
  optimization:
    batch_size: 1
    multihead_kwargs:
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.01
    num_epochs: 20
    use_bfloat16: false
    use_pos_embed: false
model_kwargs:
  checkpoint: /kaggle/working/checkpoints/vitl.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: target_encoder
      img_temporal_dim_size: null
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
